version: '3.1'

services:
  s_jenkins:
    container_name: c_jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/centos/opt/app_data/jenkins
