version: '3.1'

services:
  s_api_gateway:
    container_name: c_api_gateway
    image: candurmaz/eticaret 
    build: 
      context: .
      dockerfile: ETicaret.API/Dockerfile
    ports:
      - 80::80 
    networks: 
      - micro_net
      



networks:
  int_net:
    driver: overlay
    internal: true
  micro_net: 
    driver: bridge