version: '3.1'

services:
  s_api_geteway:
    container_name:  c_api_geteway
    build: 
      context: .
      dockerfile: ETicaret.API/Dockefile
    ports:
      - 80::80
    networks: 
      - micro_net
      



networks:
  int_net:
    driver: overlay
    internal: true
  micro_net: 
    driver: bridge